Update Beamsystem
OperationPandoraTrigger/OPT-Mission pull request #27
Opened 2019-08-06 01:06 UTC by OPTManu

Wie gestern in der EL-Sitzung festgelegt ist hier nun die Umsetzung des Beamens nach Waffenruhe mit ausgewählten Fahrzeugen.
Es kann im Setup festgelegt werden, welche Fahrzeuge dafür nutzbar sind, aktuell sind es die Quads sowie die Sanitätstrucks beider Fraktionen.
Um nach der Waffenruhe beamen zu können, muss der gewünschte Beampunkt auf Level -1 gesetzt werden, da ansonsten keine Anzeige des Punktes im Dialog erfolgt.

Zudem wurden ein paar Formfehler korrigiert und die Beschreibung verbessert

PS: Ich hoffe mal, dass das so stimmt mit GitHub, ist mein erster Versuch ^^

2019-08-06 02:17 UTC, OPTManu commented
Bitte beachten, dass in **fnc_setup_beamorte.sqf** noch die Namen der Communityflaggen fehlen und dort kein Beampunkt mit Level **-1** gesetzt war.
Ich passe die Datei mal dementsprechend an, sodass es einen Beampunkt mit Level **-1** auf jeder Seite gibt

2019-08-07 01:39 UTC, OPTManu commented on OPT_mission.Altis/beam/functions/fnc_setup_beamorte.sqf
> +	   [[4582.2017,299.6069,21385.365], "2 - Oreokastro",-1], // 2 - Oreokastro
Oreokastro auf Level -1 zum Testen der Änderungen

2019-08-07 01:40 UTC, OPTManu commented on OPT_mission.Altis/beam/functions/fnc_setup_beamorte.sqf
> +	   [[4582.2017,299.6069,21385.365], "2 - Oreokastro",-1], // 2 - Oreokastro
Oreokastro auf Level -1 zum Testen der Änderungen bei BLUFOR

2019-08-08 07:05 UTC, senshi-x requested changes
Sieht super aus. Eine kleine Anmerkung habe ich, und den "sprechenden Variablennamen" will ich unbedingt ;) . Danach werde ich approven.

2019-08-08 07:05 UTC, senshi-x commented on OPT_mission.Altis/beam/functions/fnc_setup_beamorte.sqf
> -//East
West und East sind im Code schon richtig, so nennt Arma intern die möglichen Player-Sides. Nur als Hinweis.

2019-08-08 07:05 UTC, WGPSenshi commented on OPT_mission.Altis/beam/functions/fnc_beam.sqf
> +private _kBF = true;
Bin kein Fan kryptischer Variablennamen. 
`_isVehicleBeamAllowed` oder ähnlich wäre deutlich klarer und verständlicher.

Bonuspunkte für Doku-Kommentare gibt es aber :) .

2019-08-08 11:39 UTC, OPTManu commented on OPT_mission.Altis/beam/functions/fnc_beam.sqf
> +private _kBF = true;
_kBF kam hauptsächlich daher, dass es vom Stil her sich an den anderen Variablen orientiert hat, aber du hast völlig recht, klar verständliche Variablennamen sind da natürlich besser.
Das dürfte aber auch schnell korrigiert sein ;)

2019-08-08 11:50 UTC, OPTManu commented
Änderung des Variablennamen eingebaut wie gewünscht.

2019-08-09 07:29 UTC, senshi-x approved these changes
Sieht gut aus! Als Hinweis: Conversations am besten durch den Ersteller resolven lassen. Ich hab grad gesucht, wo deine Antwort denn steckt :D .

2019-08-09 07:30 UTC, merged