Add Events for FAR (unconscious, stabilized, revived)
OperationPandoraTrigger/OPT-Mission pull request #80
Opened 2019-10-09 14:32 UTC by WGPSenshi

2019-10-09 14:57 UTC, Krzmbrzl requested changes
Ich wiederhole, was ich in der GPS-Komponente schonmal geschrieben habe:
1. Eventnamen sollten meiner Meinung nach als Konstanten (aka Makros) spezifiziert werden. Dazu würde ich im root-Ordner ein `events.hpp` anlegen und einfach in `macros.hpp` includen. Dann sind die auf jeden Fall immer verfügbar. Da kann man dann auch gleich das Preifx `opt` via Makro setzen, damit das super einfach zu verändern ist, sollte das mal benötigt sein).
In dieser Datei könnte dann auch gleich dokunmentiert werden, was für Argumente die jeweiligen Events mit verschicken.
2. Meiner Meinung nach sollten Event-Namen auch den String "Event" enthalten. Also z.B. `opt_event_unitStabilized`

Darüber hinaus könnte man sich für die Medic-Events denke ich durchaus erlauben, globale Events daraus zu machen, da
1. Der Medic-Status einer Einheit ist für alle Clients relevant (siehe z.B. GPS-Komponente)
2. Die Events treten ja nun nicht jede paar Millisekunden auf, sodass der damit verbundene Netzwerk-Traffic zu verschmerzen sein sollte.

Wenn die Events global gemacht werden, könnte man sich überlegen, ob man auch hier wieder die `netId` des Objekts statt dem Objekt direkt als Parameter übergeben will.


Ich gehe mal davon aus, dass unconcious und stabilized jeweils eine Einbahnstraße ist (also dieser Zustand kann nur durch ein Revive oder eben den Tod unterbrochen werden)?
Wenn nicht, sollten auch Events beim Verlassen des jeweiligen zustands abgesetzt werden.

2019-10-09 14:57 UTC, Krzmbrzl commented on OPT_mission.Altis/revive/functions/fnc_handlestabilize.sqf
> +        ["opt_unitStabilized",_patient] call CLib_fnc_localEvent;
Auf welcher Maschine wird dieser Code denn ausgeführt? Patient oder Retter? In beiden Fällen wäre es aber denke ich sinnvoll, wenn das Event zumindest auf beiden Clients abgesetzt wird (also nicht nur beim Einen oder beim Anderen).

2019-10-10 16:13 UTC, WGPSenshi commented on OPT_mission.Altis/revive/functions/fnc_handlestabilize.sqf
> +        ["opt_unitStabilized",_patient] call CLib_fnc_localEvent;
Ich finde Makros nach wie vor unfassbar unleserlich, insbesondere wenn sich dahinter noch ein halbes Dutzend Makros verbergen. Aber ich kann's ja mal versuchen.

2019-10-10 16:13 UTC, WGPSenshi commented on OPT_mission.Altis/revive/functions/fnc_handlestabilize.sqf
> +        ["opt_unitStabilized",_patient] call CLib_fnc_localEvent;
In Legacy werde ich Events aber nur so begrenzt wie nötig absetzen, deshalb lasse ich die erstmal local.

2019-10-10 16:16 UTC, Krzmbrzl commented on OPT_mission.Altis/revive/functions/fnc_handlestabilize.sqf
> +        ["opt_unitStabilized",_patient] call CLib_fnc_localEvent;
Naja ich weiß nicht was an `EVENT_STABILIZED` unleserlich sein sollte :man_shrugging:

2019-10-11 11:14 UTC, WGPSenshi commented on OPT_mission.Altis/revive/functions/fnc_handlestabilize.sqf
> +        ["opt_unitStabilized",_patient] call CLib_fnc_localEvent;
Das nicht, aber wie sehen die defines dafür aus? Kann ich PREFIX in einer include nutzen, wenn diese nach dem `#define` in der macros.hpp kommt (dort wird ja PREFIX eh schon definiert)?

Macht das so überhaupt Sinn? Muss ich es noch mit Quotes versehen?
```
/*
List all events used by OPT here


*/
#define OPT_EVENT(var)                  TRIPLE(PREFIX,event,var)

// FAR Medic system (legacy) compatibility events
// Unit is rendered unconscious
// params ["_unit"]
#define OPT_EVENT_MEDIC_UNCONSCIOUS     OPT_EVENT(medic_unconscious)
// Unit has been stabilized
// params ["_unit"]
#define OPT_EVENT_MEDIC_STABILIZED      OPT_EVENT(medic_stabilized)
// Unit has been revived
// params ["_unit"]
#define OPT_EVENT_MEDIC_REVIVED         OPT_EVENT(medic_revived)
```

2019-10-11 15:36 UTC, Krzmbrzl commented on OPT_mission.Altis/revive/functions/fnc_handlestabilize.sqf
> +        ["opt_unitStabilized",_patient] call CLib_fnc_localEvent;
> Kann ich PREFIX in einer include nutzen, wenn diese nach dem #define in der macros.hpp kommt (dort wird ja PREFIX eh schon definiert)?

Ja kannst du. Include-statements kannst du dir als einfache copy&pase operationen vorstellen. Dh. die `macros.hpp` wird einfach an der entsprechenden Stelle eingefügt und da diese `PREFIX` definiert, ist das Makro auch nach dem include im eifentlichen Dokument gültig.

> Muss ich es noch mit Quotes versehen?

Jein - also man muss noch wutoes einfügen, damit die Dinger nachher als Strings im Code auftauchen und SQF damit umgehen kann. Aber wenn du da einfach Quotes drum machst, verhinderst du, dass der Preprocessor korrekt arbeitet (tut er in Strings nämlich nicht). Dh. du musst den `#` operator verwenden. Oder noch einfacher: Das `QUOTE` Makro aus CLib:

```
/*
List all events used by OPT here
*/
#define OPT_EVENT(var)                  QUOTE(TRIPLE(PREFIX,event,var))

// FAR Medic system (legacy) compatibility events
// Unit is rendered unconscious
// params ["_unit"]
#define EVENT_MEDIC_UNCONSCIOUS     OPT_EVENT(medic_unconscious)
// Unit has been stabilized
// params ["_unit"]
#define EVENT_MEDIC_STABILIZED      OPT_EVENT(medic_stabilized)
// Unit has been revived
// params ["_unit"]
#define EVENT_MEDIC_REVIVED         OPT_EVENT(medic_revived)
```

Der `OPT`-Prefix f+r die _defines_ ist übrigens komplett unnötig. Diese defines existieren ja nur in den Dateien, in denen die entsprechende Datei included wurde. Da das in 3rd-party code nicht der Fall sein wird, kann das auch nicht zu name-clashes führen. Den Präfix in den eigentlichen "Event-String" mit rein zu nehmen ist dagegen wichtig, da das ja vergleichbar mit ner globalen Variable ist (es könnte ja auch sine, dass fremder Code ebenfalls die Clib-Events verwendet. Somit gibt es da also einen geteilten Namespace).

2019-10-13 07:19 UTC, WGPSenshi commented
@Krzmbrzl Fehlt hier noch etwas?

2019-10-13 07:19 UTC, Krzmbrzl requested changes

2019-10-13 07:19 UTC, Krzmbrzl commented on OPT_mission.Altis/revive/functions/fnc_handlerevive.sqf
> +        [EVENT_MEDIC_REVIVED,_patient] call CLib_fnc_localEvent;
Gilt auch für die weiteren Medic-Events: Wollten wir die jetzt nicht global machen?

2019-10-13 07:21 UTC, WGPSenshi commented on OPT_mission.Altis/revive/functions/fnc_handlerevive.sqf
> +        [EVENT_MEDIC_REVIVED,_patient] call CLib_fnc_localEvent;
Nope, erstmal nicht. Ist ja eh ein Legacy-Modul, das noch nichtmal ein Rewrite-Konzept hat.

2019-10-13 07:21 UTC, Krzmbrzl commented on OPT_mission.Altis/revive/functions/fnc_handlerevive.sqf
> +        [EVENT_MEDIC_REVIVED,_patient] call CLib_fnc_localEvent;
alles klar

2019-10-13 07:21 UTC, Krzmbrzl approved these changes

2019-10-13 07:22 UTC, merged