Gui message
OperationPandoraTrigger/OPT-Mission pull request #86
Opened 2019-10-18 23:08 UTC by formtapez

Fix für https://github.com/OperationPandoraTrigger/OPT-Server-Mod/issues/39

GUI-Messages (z.B. bei Ausrüstungs-Kauf) 
- überdecken nicht mehr das Mausrad-Menü, da nun auf rechter Bildschirmseite
- bleiben nur noch 7 statt 15 Sekunden sichtbar.
- scrollen 3-fach schneller zur Seite, wenn neue Meldungen kommen.
- zeigen auch an wenn für Bestellungen kein Platz verfügbar ist. Das war vorher per hint gelöst und hat irgendwie auch gar nicht mehr funktioniert.

2019-10-20 18:22 UTC, senshi-x requested changes

2019-10-20 18:22 UTC, WGPSenshi commented on OPT_mission.Altis/gui/config/definegrids.hpp
> +#define GUI_MSG_X (safeZoneW + safeZoneX - GUI_MSG_W)
Wie wärs, die Position konfigurierbar zu machen? Jeder hat ein anderes UI-Layout, insofern wäre es doch am besten, die Positionierung via Variable und CBA-Settings zu ermöglichen. Also zumindest die einfachen Optionen "Links/Rechts".

2019-10-26 21:08 UTC, formtapez commented on OPT_mission.Altis/gui/config/definegrids.hpp
> +#define GUI_MSG_X (safeZoneW + safeZoneX - GUI_MSG_W)
Ist nun konfigurierbar.

2019-10-29 07:15 UTC, WGPSenshi commented
Ist der PR fertig zum mergen? Wenn ja, solltest du oben ein Review "re-requesten", damit ich es mitbekomme :) .

2019-10-31 12:09 UTC, senshi-x requested changes
Nur noch eine Kleinigkeit ist mir aufgefallen. Inline-Funktionen sind bööööse :) .

2019-10-31 12:09 UTC, WGPSenshi commented on OPT_mission.Altis/gui/functions/fnc_message.sqf
> +getGuiX = { // input: GUI-IDC --> output: X-coordinate (based on left/right CBA-setting)
Bitte keine Inline-Funktionen als Variablen. Auch wenn es nur simpler Code ist, separate Funktions-Dateien machen alles deutlich übersichtlicher.

2019-10-31 16:21 UTC, formtapez commented on OPT_mission.Altis/gui/functions/fnc_message.sqf
> +getGuiX = { // input: GUI-IDC --> output: X-coordinate (based on left/right CBA-setting)
Okay, wieder was gelernt.

2019-10-31 16:23 UTC, senshi-x approved these changes

2019-10-31 16:26 UTC, merged