OPT Mission Version 1.4.15.6.carrier#1.15
OperationPandoraTrigger/OPT-Mission pull request #9
Opened 2019-07-22 12:18 UTC by GNCLORD-MDB

OPT Mission von Funschlacht 2 mit Clib Erweiterung

2019-07-22 13:43 UTC, Krzmbrzl requested changes
Was sind das alles für configs und Skripte und alles?

In diesem Repo sollte nach meinem Verständnis im Wesentlichen nur die `mission.sqm`, `description.ext` und die `init.sqf` sein.

Außerdem hat die Mission schon wieder eine Versionsnummer im Namen und hält sich somit nicht an die Vorgabe, wie dieses Repo strukturiert ist (siehe https://github.com/OperationPandoraTrigger/OPT-Mission).

2019-07-22 14:40 UTC, GNCLORD-MDB commented
> OPT Mission von Funschlacht 2 mit Clib Erweiterung 

Wie es oben steht, die Mission von Funschlacht 2.
Frozen wollte das die in Git landet, dann da die Änderungen sammelt werden können. 
Und eine Version Nummer hat die nicht ,die Vordere Nummer ist die Version der Scripte, die Mission Version Nummer habe ich vorher gelöscht (#....)
Also übernehmen bitte, wir müssen damit dann zügig die Funschlacht 3 erstellen für den Donnerstag.

2019-07-22 14:46 UTC, Krzmbrzl commented
Vllt will @Frozen-byte dann dass das in einen eigenen Branch kommt? Denn wie gesagt: Für mich sieht das hier fehl am Platz aus. Aber wenn der frozen das hier haben will, dann soll der frozen das auch selber mergen. Dann können wir uns da sicher sein, dass nix falsch interpretiert wurde ^^

Versionsnummer ist Versionsnummer. Was die im Detail nummeriert ist erstmal Wuppe. Aber in einem Versionskontrollsystem haben Versionsnummern im Namen von Dateien eigentlich nichts zu suchen (für die Versionierung ist schließlich das Versionskontrollsystem zuständig).

2019-07-23 07:02 UTC, Frozen-byte commented
Bitte noch den Branch in ein neues Ziel ändern. mit würde Legacy am besten Gefallen.

Aber es sieht so aus als ob wir die Mission noch eine ganze Weile benutzen daher will ich die nun auch im repo haben.

2019-07-23 07:25 UTC, Krzmbrzl commented
Also das target ist geändert. Nach meinem Gusto sollte aber dennoch nur komplett ohne Versionsnummer gemerged werden...

2019-07-23 09:47 UTC, Frozen-byte commented
> Also das target ist geändert. Nach meinem Gusto sollte aber dennoch nur komplett ohne Versionsnummer gemerged werden...

Da bleiben wir beim legacy Standard den zu ändern ist vergeudete Mühe. 

Ich forcemerge es nun.

2019-07-23 09:48 UTC, merged